projeto_final:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: nova
      port: 5432
      dbname: projeto
      schema: public
      threads: 4